[GH-487] implements start-stop-daemon for docker init script
[GH-487] implementing a getPid function who can detect docker daemon running without pid file

[GH-487] Adding an aggressive killing if SIGTERM is not efficient in 10 tries

No need to SIGKILL if process as stopped

[GH-487] Adding an aggressive killing if SIGTERM is not efficient in 10 tries

[GH-487] Adding an aggressive killing if SIGTERM is not efficient in 10 tries

[wip] the init script use start-stop-daemon for start and stop

Check and status are now fully working, controlling pid file and process

Tiannon protection when starting

diff --git a/rootfs/rootfs/usr/local/etc/init.d/docker b/rootfs/rootfs/usr/local/etc/init.d/docker
--- a/rootfs/rootfs/usr/local/etc/init.d/docker
+++ b/rootfs/rootfs/usr/local/etc/init.d/docker
@@ -12,6 +12,9 @@ test -f '/var/lib/boot2docker/profile' && . '/var/lib/boot2docker/profile'
 : ${DOCKER_ULIMITS:=1048576}
 : ${DOCKER_LOGFILE:=/var/lib/boot2docker/docker.log}
 
+DOCKER_SSD_PIDFILE=/var/run/docker-ssd.pid
+DOCKER_BIN=/usr/local/bin/docker
+
 : ${CERTDIR:=/var/lib/boot2docker/tls/}
 : ${CACERT:="${CERTDIR}ca.pem"}
 : ${CAKEY:="${CERTDIR}cakey.pem"}
@@ -21,6 +24,12 @@ test -f '/var/lib/boot2docker/profile' && . '/var/lib/boot2docker/profile'
 : ${KEY:="${CERTDIR}key.pem"}
 
 start() {
+
+    if check; then
+        echo >&2 'error: Docker daemon is already running; please stop it first'
+        exit 1
+    fi
+
     # Not enabling Docker daemon TLS by default.
     if [ "$DOCKER_TLS" != "" ]; then
         CERTHOSTNAMES="$(hostname -s),$(hostname -i)"
@@ -93,13 +102,22 @@ start() {
     ulimit -n $DOCKER_ULIMITS
     ulimit -p $DOCKER_ULIMITS
 
+    DOCKER_DAEMON_ARGS="-d -D -g \"$DOCKER_DIR\" -H unix:// $DOCKER_HOST $EXTRA_ARGS"
     echo "------------------------" >> "$DOCKER_LOGFILE"
-    echo "/usr/local/bin/docker -d -D -g \"$DOCKER_DIR\" -H unix:// $DOCKER_HOST $EXTRA_ARGS >> \"$DOCKER_LOGFILE\"" >> "$DOCKER_LOGFILE"
-    /usr/local/bin/docker -d -D -g "$DOCKER_DIR" -H unix:// $DOCKER_HOST $EXTRA_ARGS >> "$DOCKER_LOGFILE" 2>&1 &
+    echo "Starting Docker daemon with these args : ${DOCKER_DAEMON_ARGS}" >> "$DOCKER_LOGFILE"
+    start-stop-daemon \
+        --pidfile "$DOCKER_SSD_PIDFILE" \
+        --exec "$DOCKER_BIN" \
+        --background \
+        --make-pidfile \
+        -S \
+        -- -d -D -g "$DOCKER_DIR" -H unix:// $DOCKER_HOST $EXTRA_ARGS >> "$DOCKER_LOGFILE" 2>&1
 }
 
 stop() {
-    kill $(cat /var/run/docker.pid)
+    echo "------------------------" >> "$DOCKER_LOGFILE"
+    echo "Stopping Docker daemon."
+    start-stop-daemon --stop --pidfile "$DOCKER_SSD_PIDFILE"
 }
 
 restart() {
@@ -111,7 +129,7 @@ restart() {
 }
 
 check() {
-    [ -f /var/run/docker.pid ] && ps $(cat /var/run/docker.pid) > /dev/null 2>&1
+    [ -f "$DOCKER_SSD_PIDFILE" ] && [ $(ps | grep $(cat $DOCKER_SSD_PIDFILE) | grep -v grep | wc -l) -eq 1 ] > /dev/null 2>&1
 }
 
 status() {
