Improve docker and haveged init script pidfile handling

diff --git a/files/init.d/docker b/files/init.d/docker
--- a/files/init.d/docker
+++ b/files/init.d/docker
@@ -49,8 +49,24 @@ USERUIDGID="$(awk -F: '$1 == "docker" { print $3 ":" $4; exit }' /etc/passwd)"
 USERCFG="$USERHOME/.docker"
 
 PIDFILE='/var/run/docker.pid'
+pid() {
+	if [ -s "$PIDFILE" ]; then
+		local pid
+		pid="$(cat "$PIDFILE")"
+		if ps "$pid" > /dev/null 2>&1; then
+			echo "$pid"
+			return 0
+		fi
+	fi
+	return 1
+}
 
 start() {
+	if pid="$(pid)"; then
+		echo >&2 "error: Docker daemon is already running ($pid)"
+		exit 1
+	fi
+
 	if [ ! -e /etc/docker ]; then
 		echo 'Linking /etc/docker to /var/lib/boot2docker for persistence'
 		mkdir -p /var/lib/boot2docker/etc/docker
@@ -187,18 +203,13 @@ start() {
 	dockerd --data-root "$DOCKER_DIR" -H unix:// $EXTRA_ARGS --pidfile "$PIDFILE" >> /var/lib/boot2docker/log/docker.log 2>&1 &
 }
 
-check() {
-	[ -f "$PIDFILE" ] && ps -A -o pid | grep -q "^\s*$(cat "$PIDFILE")$" 2> /dev/null
-}
-
 stop() {
-	if check; then
-		pid=$(cat "$PIDFILE")
+	if pid="$(pid)"; then
 		echo "Stopping dockerd ($pid)"
-		kill $pid
+		kill "$pid"
 
 		i=30
-		while check; do
+		while pid > /dev/null; do
 			sleep 1
 			i=$(expr $i - 1)
 			if [ "$i" -le 0 ]; then
@@ -215,16 +226,15 @@ restart() {
 }
 
 reload() {
-	if ! check; then
+	if ! pid="$(pid)"; then
 		echo >&2 'error: Docker daemon is not running'
 		exit 1
 	fi
-	pid="$(cat "$PIDFILE")"
-	kill -s HUP $pid
+	kill -s HUP "$pid"
 }
 
 status() {
-	if check; then
+	if pid > /dev/null; then
 		echo 'Docker daemon is running'
 		exit 0
 	else
diff --git a/files/init.d/haveged b/files/init.d/haveged
--- a/files/init.d/haveged
+++ b/files/init.d/haveged
@@ -12,22 +12,42 @@ fi
 # https://github.com/jirka-h/haveged/blob/1.9.4/init.d/sysv.lsb
 
 PIDFILE='/var/run/haveged.pid'
+pid() {
+	if [ -s "$PIDFILE" ]; then
+		local pid
+		pid="$(cat "$PIDFILE")"
+		if ps "$pid" > /dev/null 2>&1; then
+			echo "$pid"
+			return 0
+		fi
+	fi
+	return 1
+}
 
 start() {
-	mkdir -p /var/lib/boot2docker/log
+	if pid="$(pid)"; then
+		echo >&2 "error: haveged is already running ($pid)"
+		exit 1
+	fi
 
 	echo 'Starting haveged'
 
+	mkdir -p /var/lib/boot2docker/log
+
 	# https://github.com/jirka-h/haveged/blob/1.9.4/init.d/sysv.lsb#L41
-	haveged -w 1024 -v 1 -p "$PIDFILE" >> /var/lib/boot2docker/log/haveged.log 2>&1
+	haveged -w 1024 -v 1 -p "$PIDFILE"
 }
 
 stop() {
-	if [ -e "$PIDFILE" ]; then
-		pid="$(cat "$PIDFILE")"
+	if pid="$(pid)"; then
 		echo "Stopping haveged ($pid)"
 		kill "$pid"
 	fi
+}
+
+restart() {
+	stop
+	start
 }
 
 # only start the daemon if it's determined that we probably need to
@@ -41,6 +61,6 @@ conditional() {
 }
 
 case "$1" in
-	start|stop|conditional) "$1" ;;
-	*) echo "Usage $0 {start|stop|conditional}"; exit 1 ;;
+	start|stop|restart|conditional) "$1" ;;
+	*) echo "Usage $0 {start|stop|restart|conditional}"; exit 1 ;;
 esac
